### ISSUE TITLE
Modify the meta class on the model for Bins

### ISSUE THREAD

**Issue by Karsonic** [dcl67/SmartCanAPI#17]
Should restrict that sId and category combination must be unique. This prevents the same category from being assigned to multiple bins in the same can.

**Comment by Karsonic** [comment]
![image](https://user-images.githubusercontent.com/24685086/37258379-9e9e8838-254d-11e8-8c96-e4aa6be0c961.png)

**Comment by dcl67** [comment]
Added unique_together("sId", "category").

See https://github.com/dcl67/SmartCanAPI/commit/c93fc8503198c8736a88c9f512056aa62d97d155
