### ISSUE TITLE
Create base.html for template html files to build on

### ISSUE THREAD

**Issue by dcl67** [dcl67/SmartCanAPI#19]

**Comment by dcl67** [comment]
I added some general comments in the base.html file I pushed in commit https://github.com/dcl67/SmartCanAPI/commit/509826c05dc930ddd73eb254ded111278cccf761 , but some are below:

The way base.html works is it acts as a parent html file, but makes adding generic elements
to each of our pages fairly simple.
This doc page is outdated, but for more good info see 
https://docs.djangoproject.com/en/1.7/topics/templates/ 

CSS is loaded into your base.html and carries to each file that extends it. Same deal with the header, content tag, and footer.
The big difference for your file is that, instead of <body> tags, you now use {% block content %} tags, which override the content block and div you have below.

**Comment by dcl67** [comment]
Also meant to say we can keep this open if we want to continue modifying it as we go along, or if we want to keep the design it has for now I can close this.

**Comment by Karsonic** [comment]
If you've added the one we're staying with you can close this. We can just
update the file as needed, no need to leave this open.

**Comment by dcl67** [comment]
Got it
